### ISSUE TITLE
Add Kubernetes Configuration Files

### ISSUE THREAD

**Issue by ztl2** [CSCI-GA-2820-FA24-003/orders#53]
**As a** programmer
**I need** necessary Kubernetes configuration files 
**So that** to enable deployment. 
   
 ### Details and Assumptions
 * Create deployment.yaml, service.yaml, ingress.yaml, and other Kubernetes configuration files.
Under the ./k8s folder, create a postgres/ folder with the StatefulSet YAML for PostgreSQL.
   
 ### Acceptance Criteria  
   
 ```gherkin
Configuration files are stored in the correct paths and can be applied with kubectl apply -f k8s.
```

**Comment by ChiChasesCheese** [comment]
Memo: Add this to meet the needs for `Add Health Check Endpoint #54`, if this story'd be merged ahead of that.
```yml
 livenessProbe:
   httpGet:
     path: /health
     port: 80
   initialDelaySeconds: 5
   periodSeconds: 10
 readinessProbe:
   httpGet:
     path: /health
     port: 80
   initialDelaySeconds: 5
   periodSeconds: 10
```
